# Generated by Django 4.1.1 on 2023-02-05 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Riddle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('riddle', models.TextField(verbose_name='Topishmoq qanday ❓')),
                ('holati', models.CharField(choices=[('osson', 'Ossonroq'), ("o'rtacha", "O'rtacha"), ('qiyin', 'Qiyin')], max_length=50)),
                ('javobi', models.CharField(max_length=80)),
                ('vaqti', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
