# Generated by Django 4.1.1 on 2023-02-05 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riddle',
            name='riddle',
            field=models.TextField(verbose_name='Topishmoq qanday'),
        ),
    ]
