# Generated by Django 4.1.1 on 2023-02-06 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jokes', '0002_alter_riddle_riddle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v1', models.CharField(max_length=80, verbose_name='1-variant')),
                ('v2', models.CharField(max_length=80, verbose_name='2-variant')),
                ('v3', models.CharField(max_length=80, verbose_name='3-variant')),
                ('v4', models.CharField(max_length=80, verbose_name='4-variant')),
                ('vaqti', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
