# Generated by Django 4.1.1 on 2023-02-06 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jokes', '0003_variant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Variant',
        ),
    ]
