# Generated by Django 4.1.1 on 2023-02-11 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turi', models.CharField(choices=[('easy', 'Osson'), ('normal', "O'rtacha"), ('hard', 'Qiyin')], max_length=120, verbose_name='Qiyinlik darajasi')),
                ('quiz', models.TextField(verbose_name='Savolni kiriting ')),
                ('answer', models.CharField(max_length=300, verbose_name="To'g'ri javob")),
                ('option1', models.CharField(max_length=300, verbose_name='Birinchi variant')),
                ('option2', models.CharField(max_length=300, verbose_name='Ikkinchi variant')),
                ('option3', models.CharField(max_length=300, verbose_name='Uchinchi variant')),
                ('option4', models.CharField(max_length=300, verbose_name="To'ritnchi variant")),
                ('status', models.CharField(choices=[('see', "Ko'rsatish"), ('notsee', 'Yashirish')], max_length=120, verbose_name='Holati')),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
